[package]
name = "bit-touying-templates"
version = "0.1.0"
entrypoint = "template.typ"
authors = ["Ri_Nai_@outlook.com"]
license = "MIT"
description = ""
homepage = "https://github.com/Ri-Nai/BIT-Typst-Template"
repository = "https://github.com/Ri-Nai/BIT-Typst-Template"
keywords = ["slides", "BIT", "Beijing Institute of Technology"]
categories = ["slides"]

[template]
path = "template"
entrypoint = "main.typ"
description = "A Typst template for undergraduate slides of Beijing Institute of Technology."
